spring:
  application:
    name: order-system

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    kr.minigate.ordersystem: DEBUG

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
  info:
    title: Order System API
    description: |
      ## 주문 시스템 REST API

      이 API는 온라인 주문 시스템을 위한 RESTful 웹 서비스입니다.

      ### 주요 기능
      - **회원 관리**: 회원 등록, 조회, 수정, 삭제
      - **상품 관리**: 상품 등록, 조회, 재고 관리
      - **주문 관리**: 주문 생성, 조회, 상태 변경, 취소
      - **결제 관리**: 결제 처리, 조회, 환불, 취소

      ### 인증
      현재 버전에서는 별도의 인증이 필요하지 않습니다.

      ### 응답 형식
      모든 API는 JSON 형식으로 응답합니다.

      ### 에러 코드
      - **400**: 잘못된 요청 (Bad Request)
      - **404**: 리소스를 찾을 수 없음 (Not Found)
      - **500**: 서버 내부 오류 (Internal Server Error)

      ### 연락처
      - **이메일**: support@ordersystem.com
      - **GitHub**: https://github.com/minigate/order-system
    version: v1.0.0
    contact:
      name: Order System Team
      email: support@ordersystem.com
      url: https://github.com/minigate/order-system
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT
  servers:
    - url: http://localhost:8080
      description: 개발 서버
    - url: https://api.ordersystem.com
      description: 운영 서버